version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway  # Ruta al directorio donde está el Dockerfile del API Gateway
    ports:
      - "8082:8081"  # Expone el puerto 8081 del contenedor en el puerto 8081 de tu máquina
    depends_on:
      - ucobet-generales  # Aquí debe coincidir el nombre del servicio del backend
    networks:
      - uco-net
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}

  ucobet-generales:
    build:
      context: ./ucobet-generales  # Ruta al directorio donde está el Dockerfile del backend
    ports:
      - "8083:8443"  # Expone el puerto 8443 del contenedor en el puerto 8443 de tu máquina
    networks:
      - uco-net
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}

networks:
  uco-net:
    driver: bridge
